transisi_laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix' => 'Administrator', 'middleware' => 'auth'], function () {
    Route::resource('home', 'CompaniesController');
    Route::resource('employees', 'EmployeesController');
});

transisi_laravel/resources/views/employe/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row justify-content-center">
    <div class="col-md-6 card">
        <div class="text-center">
            <h1>Tambah Data Companies</h1><br>
        </div>
       
        <form method="POST" action="{{ route('employees.store') }}">
            @csrf
            <div class="form-group">
              <label for="formGroupExampleInput">Nama</label>
              <input type="text" name="nama" class="form-control" id="formGroupExampleInput" placeholder="Masukan Nama Employees" value="{{ old('nama') }}">
              @error('nama')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="companies_id">Companies</label>
                <select name="companies_id" class="form-control">
                    <option value="">Pilih</option>
                    @foreach ($companies as $row)
                    <option value="{{ $row->id }}" {{ old('companies_id') == $row->id ? 'selected':'' }}>{{ $row->nama }}</option>
                    @endforeach
                </select>
                @error('companies_id')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Email</label>
              <input type="email" name="email" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Email Employees" value="{{ old('email') }}">
              @error('email')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>

              <div class="text-right">
                <a class="btn btn-success mt-2" href="{{ route('employees.index') }}">Kembali</a>
                  <button type="submit" class="btn btn-primary mt-4 mb-3 mr-2" >Simpan</button>
              </div>
          </form>
    </div>
</div>
    
@endsection

transisi_laravel/resources/views/employe/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6 card">
        <div class="text-center">
            <h1>Edit Data Employees</h1><br>
        </div>
       
        <form method="POST" action="{{ route('employees.update', $employees->id) }}">
            @method('put')
            @csrf
            <div class="form-group">
              <label for="formGroupExampleInput">Nama</label>
              <input type="text" name="nama" class="form-control" id="formGroupExampleInput" value="{{ $employees->nama }}">
              @error('nama')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="category_id">Compaines</label>
                <select name="companies_id" class="form-control">
                    <option value="">Pilih</option>
                    @foreach ($companies as $row)
                    <option value="{{ $row->id }}" {{ $employees->companies_id == $row->id ? 'selected':'' }}>{{ $row->nama }}</option>
                    @endforeach
                </select>
                @error('companies_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Email</label>
              <input type="email" name="email" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Email Employees" value="{{ $employees->email }}">
              @error('email')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>

              <div class="text-right">
                <a class="btn btn-success mt-2" href="{{ route('employees.index') }}">Kembali</a>
                  <button type="submit" class="btn btn-primary mt-4 mb-3 mr-2" >Simpan</button>
              </div>
          </form>
    </div>
</div>
    
@endsection

transisi_laravel/resources/views/employe/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <ul class="list-group list-group-horizontal justify-content-center">
                <li class="list-group-item"><a href="{{ route('home.index') }}">Company</a></li>
                <li class="list-group-item"><a href="{{ route('employees.index') }}">Employe</a></li>
            </ul>
    
            <a class="btn btn-primary mb-3 mt-2" href="{{ route('employees.create') }}">Tambah Employe</a>
            <div class="card">
                <div class="card-header"><h3>Data Employees</h3></div>
                <div class="card-body">
                    <div class="row">
                        
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Nama</th>
                                    <th scope="col">Company</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Aksi</th>
                                </tr>
                            </thead>
                            @forelse ($employe as $row)
                            <tbody>
                              <tr>
                                <th scope="row">{{ $row->nama }}</th>
                                <td>{{ $row->companies->nama }}</td>
                                <td>{{ $row->email }}</td>
                                <td>
                                    <form method="POST" action="{{ route('employees.destroy' , $row->id) }}">
                                        @csrf
                                        @method('delete')
                                        
                                        <a class="btn btn-warning" href="{{ route('employees.edit', $row->id) }}">Edit</a>
                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                      </form>
                                </td>
                              </tr>
                        @empty
                        <td colspan="5">Data Masih Kosong</td>
                        @endforelse
                        </tbody>
                    </table>
    
                    {{ $employe->links() }}
                        
                        
                 </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection