transisi_laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix' => 'Administrator', 'middleware' => 'auth'], function () {
    Route::resource('home', 'CompaniesController');
    Route::resource('employees', 'EmployeesController');
});

transisi_laravel/resources/views/addcompany.blade.php
@extends('layouts.app')

@section('content')

<div class="row justify-content-center">
    <div class="col-md-6 card">
        <div class="text-center">
            <h1>Tambah Data Companies</h1><br>
        </div>
       
        <form method="POST" action="{{ route('home.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label for="formGroupExampleInput">Nama</label>
              <input type="text" name="nama" class="form-control" id="formGroupExampleInput" placeholder="Masukan Nama Companies" value="{{ old('nama') }}">
              @error('nama')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Email</label>
              <input type="email" name="email" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Email Companies" value="{{ old('email') }}">
              @error('email')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Alamat Website</label>
              <input type="text" name="website" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Alamat Website" value="{{ old('website') }}">
              @error('website')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="custom-file">
                <input type="file" name="logo" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">File Logo</label>
                @error('logo')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>

              <div class="text-right">
                <a class="btn btn-success mt-2" href="{{ route('home.index') }}">Kembali</a>
                  <button type="submit" class="btn btn-primary mt-4 mb-3 mr-2" >Simpan</button>
              </div>
          </form>
    </div>
</div>
    
@endsection

transisi_laravel/resources/views/editcompanies.blade.php
@extends('layouts.app')

@section('content')

<div class="row justify-content-center">
    <div class="col-md-6 card">
        <div class="text-center">
            <h1>Edit Data Companies</h1><br>
        </div>
       
        <form method="POST" action="{{ route('home.update', $companies->id) }}" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="form-group">
              <label for="formGroupExampleInput">Nama</label>
              <input type="text" name="nama" class="form-control" id="formGroupExampleInput" value="{{ $companies->nama }}">
              @error('nama')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Email</label>
              <input type="email" name="email" class="form-control" id="formGroupExampleInput2" value="{{ $companies->email }}">
              @error('email')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput2">Alamat Website</label>
              <input type="text" name="website" class="form-control" id="formGroupExampleInput2" placeholder="Masukan Alamat Website" value="{{ $companies->website }}">
              @error('website')
              <div class="alert alert-danger">{{ $message }}</div>
              @enderror
            </div>
            <img width="100" height="100" src="{{ asset('storage/app/company/' . $companies->logo) }}" alt="">
            <div class="custom-file mt-2">
                <input type="file" name="logo" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Abaikan Jika Tidak ingin Mengubah Logo</label>
                @error('logo')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>

              <div class="text-right">
                  <a class="btn btn-success mt-2" href="{{ route('home.index') }}">Kembali</a>
                  <button type="submit" class="btn btn-primary mt-4 mb-3 mr-2" >Simpan</button>
              </div>
          </form>
    </div>
</div>
    
@endsection

transisi_laravel/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <ul class="list-group list-group-horizontal justify-content-center">
                <li class="list-group-item"><a href="{{ route('home.index') }}">Company</a></li>
                <li class="list-group-item"><a href="{{ route('employees.index') }}">Employe</a></li>
            </ul>

            <a class="btn btn-primary mb-3 mt-2" href="{{ route('home.create') }}">Tambah Companies</a>
            <div class="card">
                <div class="card-header"><h3>Data Companie</h3></div>
                <div class="card-body">
                    <div class="row">
                        
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Nama</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Website</th>
                                    <th scope="col">Logo</th>
                                    <th scope="col">Aksi</th>
                                </tr>
                            </thead>
                            @forelse ($companies as $row)
                            <tbody>
                              <tr>
                                <th scope="row">{{ $row->nama }}</th>
                                <td>{{ $row->email }}</td>
                                <td>{{ $row->website }}</td>
                                <td><img src="{{ asset('storage/app/company/'. $row->logo) }}"></td>
                                <td>
                                    <form method="POST" action="{{ route('home.destroy' , $row->id) }}">
                                        @csrf
                                        @method('delete')
                                        
                                        <a class="btn btn-warning" href="{{ route('home.edit', $row->id) }}">Edit</a>
                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                      </form>
                                </td>
                              </tr>
                        @empty
                        <td colspan="5">Data Masih Kosong</td>
                        @endforelse
                        </tbody>
                    </table>

                    {{ $companies->links() }}
                        
                        
                 </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection